-- 코드를 입력하세요
#USER_INFO와 ONLINE_SALE 테이블에서 년, 월, 성별 별로 상품을 구매한 회원수를 집계
SELECT YEAR(O.SALES_DATE) AS YEAR, MONTH(O.SALES_DATE) AS MONTH, U.GENDER AS GENDER, COUNT(DISTINCT U.USER_ID) AS USERS

FROM USER_INFO U

JOIN ONLINE_SALE O

ON U.USER_ID = O.USER_ID

WHERE U.GENDER IS NOT NULL

GROUP BY YEAR(O.SALES_DATE), MONTH(O.SALES_DATE), U.GENDER

ORDER BY YEAR, MONTH, GENDER
