-- 코드를 입력하세요
# 보호 시작일보다, 입양일이 더 빠른 동물의 아이디와 이름을 조회하는 SQL문

SELECT AI.ANIMAL_ID, AI.NAME
FROM ANIMAL_INS AI
JOIN ANIMAL_OUTS AO
ON AI.ANIMAL_ID = AO.ANIMAL_ID
WHERE AO.DATETIME < AI.DATETIME
ORDER BY AI.DATETIME ASC
