-- 코드를 작성해주세요
# 2022년도 한해 평가 점수가 가장 높은 사원 정보를 조회
# 점수, 사번, 성명, 직책, 이메일(HR_EMPLOYEE)
SELECT SUM(SCORE) AS SCORE, E.EMP_NO, E.EMP_NAME, E.POSITION, E.EMAIL
FROM HR_EMPLOYEES E
JOIN HR_GRADE G
ON E.EMP_NO = G.EMP_NO
GROUP BY G.EMP_NO
ORDER BY SCORE DESC
LIMIT 1

