-- 코드를 입력하세요
# FIRST_HALF의 기본키는 FLAVOR
# ICECREAM_INFO 기본키는 FLAVOR이자 FIRST_HALF의 외래키이다.
# 아이스크림의 성분 타입과, 성분 타입에 대한 아이스크림의 총 주문량을 총 주문량이 작은 순서대로 조회

SELECT INGREDIENT_TYPE, SUM(TOTAL_ORDER) AS TOTAL_ORDER
FROM FIRST_HALF F
JOIN ICECREAM_INFO I
ON F.FLAVOR = I.FLAVOR
GROUP BY I.INGREDIENT_TYPE
ORDER BY TOTAL_ORDER;
